### ISSUE TITLE
page reloading when clicking on the link in the left panel.

### ISSUE THREAD

**Issue by vikram-triculin** [Triculin/Tiny360-rc5#11]
@Bhavana-Triculin   please check in to the issue asap

**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

**Steps to reproduce and a minimal demo of the problem**

_What steps should we try in your demo to see the problem?_

**Current behavior**

**Expected/desired behavior**

**Other information**

**Comment by Bhavana-Triculin** [comment]
i have resolved that issue ,

its because the anchor tag containing # in the herf, thats why its reloading.
uploaded the code in to the new branch 29092016b
