### ISSUE TITLE
distorting UI : datatable

### ISSUE THREAD

**Issue by vikram-triculin** [Triculin/Tiny360-rc5#13]
@lakshman-triculin  please look into the pages and styles are not applying to the data , please check the issue and update the code asap.

**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

**Steps to reproduce and a minimal demo of the problem**

_What steps should we try in your demo to see the problem?_

**Current behavior**

**Expected/desired behavior**

**Other information**

**Comment by lakshman-triculin** [comment]
ok i will do,update pagination  with styles for data tables
